name: Security Scan

on: [push]

jobs:
  bandit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
    - name: Install Bandit
      run: pip install bandit
    - name: Run Bandit
      run: bandit -c pyproject.toml -r src
