name: Mypy Type Check
on: push

jobs:
  mypy:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
    - name: Install packages
      run: pip install -r requirements.txt
    - name: Run Mypy
      run: mypy . --html-report mypy-report
    - name: Archive coverage artifacts
      uses: actions/upload-artifact@v4
      with:
        name: mypy report
        path: |
          mypy-report
        retention-days: 2
