name: Unittest Coverage
on: push

jobs:
  unittest:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
    - name: Install Poetry
      run: pip install poetry
    - name: Install packages
      run: poetry install
    - name: Run Unittests
      run: poetry run pytest --cov=./python_boilerplate --cov-report html:coverage-report
    - name: Archive coverage artifacts
      uses: actions/upload-artifact@v4
      with:
        name: coverage report
        path: |
          coverage-report
        retention-days: 2
