name: Unittest Coverage
on: push

jobs:
  unittest:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - name: Install packages
      run: pip install -r requirements.txt
    - name: Run Unittests
      run: pytest --cov=./src --cov-report html:coverage-report
    - name: Archive coverage artifacts
      uses: actions/upload-artifact@v4
      with:
        name: coverage report
        path: |
          coverage-report
